import { apiClient } from "@/lib/http/api-client";
import { API_ENDPOINTS } from "@/constants/api";

const q = (params = {}) => ({ params: Object.fromEntries(Object.entries(params).filter(([, v]) => v !== "" && v !== undefined && v !== null)) });

export const authApi = {
  login: (payload) => apiClient.post(API_ENDPOINTS.auth.login, payload),
  me: () => apiClient.get(API_ENDPOINTS.auth.me),
  refresh: () => apiClient.post(API_ENDPOINTS.auth.refresh),
  logout: () => apiClient.post(API_ENDPOINTS.auth.logout),
};

export const adminApi = {
  dashboard: () => apiClient.get(API_ENDPOINTS.admin.dashboard),
  getProfile: () => apiClient.get(API_ENDPOINTS.admin.profile),
  requestPasswordChange: (payload) => apiClient.post(API_ENDPOINTS.admin.requestPasswordChange, payload),
  verifyPasswordChange: (payload) => apiClient.post(API_ENDPOINTS.admin.verifyPasswordChange, payload),
  listNotificationRecipients: () => apiClient.get(API_ENDPOINTS.admin.notificationRecipients),
  createNotificationRecipient: (payload) => apiClient.post(API_ENDPOINTS.admin.notificationRecipients, payload),
  verifyNotificationRecipient: (payload) => apiClient.post(API_ENDPOINTS.admin.verifyNotificationRecipient, payload),
  toggleNotificationRecipient: (uuid) => apiClient.patch(`${API_ENDPOINTS.admin.notificationRecipients}/${uuid}/toggle`),
  deleteNotificationRecipient: (uuid) => apiClient.delete(`${API_ENDPOINTS.admin.notificationRecipients}/${uuid}`),
  sendNotificationRecipientTest: () => apiClient.post(API_ENDPOINTS.admin.testNotificationRecipients),
  getHomepageSettings: () => apiClient.get(API_ENDPOINTS.admin.homeSettings),
  updateHomepageSection: (id, payload) => apiClient.put(API_ENDPOINTS.admin.homepageSection(id), payload),
  toggleHomepageSection: (id, payload = {}) => apiClient.patch(API_ENDPOINTS.admin.homepageSectionToggle(id), payload),
  reorderHomepageSections: (payload) => apiClient.patch(API_ENDPOINTS.admin.homepageSectionsReorder, payload),
  addHomepageFeaturedItem: (sectionId, payload) => apiClient.post(API_ENDPOINTS.admin.homepageSectionItems(sectionId), payload),
  removeHomepageFeaturedItem: (sectionId, itemId) => apiClient.delete(API_ENDPOINTS.admin.homepageSectionItem(sectionId, itemId)),
  listBlogCategories: (params) => apiClient.get(API_ENDPOINTS.admin.blogCategories, q(params)),
  createBlogCategory: (payload) => apiClient.post(API_ENDPOINTS.admin.blogCategories, payload),
  updateBlogCategory: (uuid, payload) => apiClient.patch(`${API_ENDPOINTS.admin.blogCategories}/${uuid}`, payload),
  deleteBlogCategory: (uuid) => apiClient.delete(`${API_ENDPOINTS.admin.blogCategories}/${uuid}`),
  listBlogTags: (params) => apiClient.get(API_ENDPOINTS.admin.blogTags, q(params)),
  createBlogTag: (payload) => apiClient.post(API_ENDPOINTS.admin.blogTags, payload),
  updateBlogTag: (uuid, payload) => apiClient.patch(`${API_ENDPOINTS.admin.blogTags}/${uuid}`, payload),
  deleteBlogTag: (uuid) => apiClient.delete(`${API_ENDPOINTS.admin.blogTags}/${uuid}`),
  listBlogPosts: (params) => apiClient.get(API_ENDPOINTS.admin.blogPosts, q(params)),
  createBlogPost: (payload) => apiClient.post(API_ENDPOINTS.admin.blogPosts, payload),
  updateBlogPost: (uuid, payload) => apiClient.patch(`${API_ENDPOINTS.admin.blogPosts}/${uuid}`, payload),
  updateBlogPostFeatured: (uuid, payload) => apiClient.patch(`${API_ENDPOINTS.admin.blogPosts}/${uuid}/featured`, payload),
  publishBlogPost: (uuid) => apiClient.patch(`${API_ENDPOINTS.admin.blogPosts}/${uuid}/publish`),
  unpublishBlogPost: (uuid) => apiClient.patch(`${API_ENDPOINTS.admin.blogPosts}/${uuid}/unpublish`),
  archiveBlogPost: (uuid) => apiClient.patch(`${API_ENDPOINTS.admin.blogPosts}/${uuid}/archive`),
  deleteBlogPost: (uuid) => apiClient.delete(`${API_ENDPOINTS.admin.blogPosts}/${uuid}`),

  listProductCategories: (params) => apiClient.get(API_ENDPOINTS.admin.productCategories, q(params)),
  createProductCategory: (payload) => apiClient.post(API_ENDPOINTS.admin.productCategories, payload),
  updateProductCategory: (uuid, payload) => apiClient.patch(`${API_ENDPOINTS.admin.productCategories}/${uuid}`, payload),
  deleteProductCategory: (uuid) => apiClient.delete(`${API_ENDPOINTS.admin.productCategories}/${uuid}`),
  listProductBrands: (params) => apiClient.get(API_ENDPOINTS.admin.productBrands, q(params)),
  createProductBrand: (payload) => apiClient.post(API_ENDPOINTS.admin.productBrands, payload),
  updateProductBrand: (uuid, payload) => apiClient.patch(`${API_ENDPOINTS.admin.productBrands}/${uuid}`, payload),
  deleteProductBrand: (uuid) => apiClient.delete(`${API_ENDPOINTS.admin.productBrands}/${uuid}`),
  listProductCollections: (params) => apiClient.get(API_ENDPOINTS.admin.productCollections, q(params)),
  createProductCollection: (payload) => apiClient.post(API_ENDPOINTS.admin.productCollections, payload),
  updateProductCollection: (uuid, payload) => apiClient.patch(`${API_ENDPOINTS.admin.productCollections}/${uuid}`, payload),
  deleteProductCollection: (uuid) => apiClient.delete(`${API_ENDPOINTS.admin.productCollections}/${uuid}`),
  listProducts: (params) => apiClient.get(API_ENDPOINTS.admin.products, q(params)),
  createProduct: (payload) => apiClient.post(API_ENDPOINTS.admin.products, payload),
  updateProduct: (uuid, payload) => apiClient.patch(`${API_ENDPOINTS.admin.products}/${uuid}`, payload),
  updateProductFeatured: (uuid, payload) => apiClient.patch(`${API_ENDPOINTS.admin.products}/${uuid}/featured`, payload),
  activateProduct: (uuid) => apiClient.patch(`${API_ENDPOINTS.admin.products}/${uuid}/activate`),
  deactivateProduct: (uuid) => apiClient.patch(`${API_ENDPOINTS.admin.products}/${uuid}/deactivate`),
  updateProductStatus: (uuid, status) => apiClient.patch(`${API_ENDPOINTS.admin.products}/${uuid}/status`, { status }),
  archiveProduct: (uuid) => apiClient.patch(`${API_ENDPOINTS.admin.products}/${uuid}/archive`),
  deleteProduct: (uuid) => apiClient.delete(`${API_ENDPOINTS.admin.products}/${uuid}`),

  listMedia: (params) => apiClient.get(API_ENDPOINTS.admin.media, q(params)),
  uploadImage: (formData) => apiClient.post(`${API_ENDPOINTS.admin.media}/images`, formData, { headers: { "Content-Type": "multipart/form-data" } }),
  previewProductImport: (formData) => apiClient.post(API_ENDPOINTS.admin.previewProductImport, formData, { headers: { "Content-Type": "multipart/form-data" } }),
  confirmProductImport: (uuid) => apiClient.post(API_ENDPOINTS.admin.confirmProductImport(uuid)),
  importProducts: (formData) => apiClient.post(API_ENDPOINTS.admin.importProducts, formData, { headers: { "Content-Type": "multipart/form-data" } }),
  listImportJobs: (params) => apiClient.get(API_ENDPOINTS.admin.importJobs, q(params)),
  downloadProductImportTemplate: () => apiClient.get(API_ENDPOINTS.admin.productImportTemplate, { responseType: "blob", headers: { Accept: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" } }),
};
