export const API_TIMEOUT_MS = 30_000;

export const API_ENDPOINTS = Object.freeze({
  auth: {
    login: "/auth/login",
    me: "/auth/me",
    refresh: "/auth/refresh",
    logout: "/auth/logout",
  },
  admin: {
    dashboard: "/admin/dashboard",
    profile: "/admin/profile",
    requestPasswordChange: "/admin/profile/change-password/request",
    verifyPasswordChange: "/admin/profile/change-password/verify",
    notificationRecipients: "/admin/notification-recipients",
    homeSettings: "/admin/homepage",
    homepageSection: (id) => `/admin/homepage/sections/${id}`,
    homepageSectionToggle: (id) => `/admin/homepage/sections/${id}/toggle`,
    homepageSectionsReorder: "/admin/homepage/sections/reorder",
    homepageSectionItems: (id) => `/admin/homepage/sections/${id}/items`,
    homepageSectionItem: (sectionId, itemId) => `/admin/homepage/sections/${sectionId}/items/${itemId}`,
    verifyNotificationRecipient: "/admin/notification-recipients/verify",
    testNotificationRecipients: "/admin/notification-recipients/test",
    blogCategories: "/admin/blog/categories",
    blogTags: "/admin/blog/tags",
    blogPosts: "/admin/blog/posts",
    productCategories: "/admin/products/categories",
    productBrands: "/admin/products/brands",
    productCollections: "/admin/products/collections",
    products: "/admin/products",
    media: "/admin/media",
    importJobs: "/admin/imports",
    importProducts: "/admin/imports/products",
    productImportTemplate: "/admin/imports/products/template",
    previewProductImport: "/admin/imports/products/preview",
    confirmProductImport: (uuid) => `/admin/imports/products/${uuid}/confirm`,
  },
});
